### ISSUE TITLE
No logo shown for Klarna Payments in Order Confirmation emails

### ISSUE THREAD

**Issue by hundebol** [QuickPay/magento-v1#2]
Customers who pay with Klarna Payments, get an invalid image in their order confirmation emails and on the order in backend.
![klarna](https://user-images.githubusercontent.com/3016326/96585458-edb4fb00-12df-11eb-8b39-7248ffa4eeaa.png)
![mastercard](https://user-images.githubusercontent.com/3016326/96585461-ee4d9180-12df-11eb-92c0-95b939c995a5.png)

It seems you are saving the cardtype for all payment types, but for Klarna Payments nothing is written in the tables.
Line 175 here:
https://github.com/QuickPay/magento-v1/blob/master/app/code/community/Quickpay/Payment/controllers/PaymentController.php

**Comment by CodemakersDK** [comment]
It is now available in 3.5.1
