### ISSUE TITLE
Paypal and ApplePay logos not available

### ISSUE THREAD

**Issue by anielsensalecto** [QuickPay/magento-v1#3]
As per coding, ApplePay and Paypal logos should be available in newest module release.

This is not the case.

Can someone let me know, why they are not available?
https://www.loom.com/share/e1c266a9eaea4fa09f4c0c1741f63dbd

[magento-v1-master.zip](https://github.com/QuickPay/magento-v1/files/5588516/magento-v1-master.zip)
![2020-11-24 09_49_41-Window](https://user-images.githubusercontent.com/74957308/100070713-863c1f00-2e3a-11eb-9b99-fe664dba514f.png)

**Comment by CodemakersDK** [comment]
They are now available in 3.5.1
