### ISSUE TITLE
Wrong version number 

### ISSUE THREAD

**Issue by julianchristmas** [QuickPay/magento-v1#4]
**Version number for the current master version should be 3.5.0 and not 3.4.5** 

As stated in [config.xml](https://github.com/QuickPay/magento-v1/blob/77c906a024d38f749fe6368a940d4cbd89090a36/app/code/community/Quickpay/Payment/etc/config.xml#L5)

Marek changed version number from 3.4.9 to 3.4.5 in [77c906a024d38f749fe6368a940d4cbd89090a36](https://github.com/QuickPay/magento-v1/commit/77c906a024d38f749fe6368a940d4cbd89090a36)

The update should have been to 3.5.0 as, 3.4.9 was published with his prior commit [64c6469975a10f60e6a2c97707ddd704160c4d0b](https://github.com/QuickPay/magento-v1/commit/64c6469975a10f60e6a2c97707ddd704160c4d0b)

This is a minor thing, but messes with troubleshooting errors :-)

**Comment by CodemakersDK** [comment]
Thanks for pointing it out. Current version number has now been updated to 3.5.0.
